server:
  name: "TikTokRabbitMQServer"
  host: 0.0.0.0
  port: 5672
  username: tiktokRMQ
  password: tiktokRMQ
  vhost: tiktokRMQ

consumer:
  favorite:
    autoAck: true
    prefetchCount: 1000
  relation:
    autoAck: true
    prefetchCount: 1000